name: Build

on:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "docker/**"
      - "*.sh"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "docker/**"
      - "build.sh"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build_manylinux:
    name: ${{ matrix.policy }}_${{ matrix.platform }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        policy: ["manylinux2014"]
        platform: ["x86_64"]

    env:
      POLICY: ${{ matrix.policy }}
      PLATFORM: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./build.sh

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: ghcr.io/femorph/${POLICY}_${PLATFORM}:python310